schema_version = "1.0.0"
id = "lost_saga_io3d"
version = "1.5.0"
name = "Lost Saga io3D Importer/Exporter"
tagline = "Import/export various Lost Saga 3D formats" 
maintainer = "Trisnox"
type = "add-on"
website = "https://github.com/Trisnox/lost-saga-io3d"
blender_version_min = "4.1.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"
license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Import/export SKL/MSH/CMS/ANI/DDS/TXT from/to disk"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/.github/",
  ".gitignore"
]
